### ISSUE TITLE
In the pros of school choice story, where we say "In 1988, Academic Magnet High was born, the first countywide magnet high school...," let's link to our graphic of the history of school choice or run it within the story. Chad or Brandon should have it.

### ISSUE THREAD

**Issue by jenniferhawes** [postandcourier/schools#18] opened 2015-08-17 15:56 UTC

**Comment by lauragaton** [comment] 2015-08-18 00:11
@jemory please comment and close when this is done.

**Comment by jemory** [comment] 2015-08-18 15:12
Appears to be duplicate of https://github.com/postandcourier/schools/issues/39

**Closed by jemory** 2015-08-18 15:12 UTC
